### ISSUE TITLE
UR5 executes partial trajectory

### ISSUE THREAD

**Issue by atenpas** [ThomasTimm/ur_modern_driver#122]
When using the **joint trajectory action** (JTA), our UR5 robot sometimes executes only a partial trajectory. There's no error message shown on the teaching pendant, and the "result" from the ROS action is "True". 

To be more precise, I can usually use the JTA a few times (2-3), executing the complete trajectory **without** problems, and then for a new goal, it only does a few steps and stops moving. The trajectories  send to the JTA consist of two points (current c-space config, target c-space config).

I've attached the output on the two ROS topics `follow_joint_trajectory/goal` and `follow_joint_trajectory/result`.

Some more info:
- **Polyscope version:** 3.1.18024
- **Firmware version:** 3.1.18024
- **ROS Indigo, Ubuntu 14.04**

`follow_joint_trajectory/goal` messages:

```yaml
header: 
  seq: 1
  stamp: 
    secs: 1500500148
    nsecs: 306981086
  frame_id: ''
goal_id: 
  stamp: 
    secs: 1500500148
    nsecs: 306955099
  id: /ur_grasping_demo-1-1500500148.307
goal: 
  trajectory: 
    header: 
      seq: 0
      stamp: 
        secs: 0
        nsecs:         0
      frame_id: ''
    joint_names: ['shoulder_pan_joint', 'shoulder_lift_joint', 'elbow_joint', 'wrist_1_joint', 'wrist_2_joint', 'wrist_3_joint']
    points: 
      - 
        positions: [-1.724776569996969, -1.4749835173236292, 1.619114875793457, -1.7477219740497034, -1.5616925398456019, 0.057179734110832214]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        effort: []
        time_from_start: 
          secs: 0
          nsecs:         0
      - 
        positions: [-0.387, -2.137, 1.432, -0.915, -1.591, 0.071]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        effort: []
        time_from_start: 
          secs: 4
          nsecs:         0
  path_tolerance: []
  goal_tolerance: []
  goal_time_tolerance: 
    secs: 0
    nsecs:         0
---
header: 
  seq: 1
  stamp: 
    secs: 1500500174
    nsecs: 764067888
  frame_id: ''
goal_id: 
  stamp: 
    secs: 1500500174
    nsecs: 764015913
  id: /ur_grasping_demo-1-1500500174.764
goal: 
  trajectory: 
    header: 
      seq: 0
      stamp: 
        secs: 0
        nsecs:         0
      frame_id: ''
    joint_names: ['shoulder_pan_joint', 'shoulder_lift_joint', 'elbow_joint', 'wrist_1_joint', 'wrist_2_joint', 'wrist_3_joint']
    points: 
      - 
        positions: [-1.4329231421100062, -1.6194341818438929, 1.578348159790039, -1.5660150686847132, -1.5681222120868128, 0.06021548807621002]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        effort: []
        time_from_start: 
          secs: 0
          nsecs:         0
      - 
        positions: [-0.387, -2.137, 1.432, -0.915, -1.591, 0.071]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        effort: []
        time_from_start: 
          secs: 4
          nsecs:         0
  path_tolerance: []
  goal_tolerance: []
  goal_time_tolerance: 
    secs: 0
    nsecs:         0
---
header: 
  seq: 2
  stamp: 
    secs: 1500500179
    nsecs:   4246950
  frame_id: ''
goal_id: 
  stamp: 
    secs: 1500500179
    nsecs:   4204988
  id: /ur_grasping_demo-2-1500500179.004
goal: 
  trajectory: 
    header: 
      seq: 0
      stamp: 
        secs: 0
        nsecs:         0
      frame_id: ''
    joint_names: ['shoulder_pan_joint', 'shoulder_lift_joint', 'elbow_joint', 'wrist_1_joint', 'wrist_2_joint', 'wrist_3_joint']
    points: 
      - 
        positions: [-0.3860085646258753, -2.1375158468829554, 1.4319119453430176, -0.9144766966449183, -1.5910165945636194, 0.07101514935493469]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        effort: []
        time_from_start: 
          secs: 0
          nsecs:         0
      - 
        positions: [-2.167712724147721, -2.849651400553423, 0.3850272898179735, 0.2795094791247441, -1.1638632230939256, -0.4661516591390127]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        effort: []
        time_from_start: 
          secs: 4
          nsecs:         0
  path_tolerance: []
  goal_tolerance: []
  goal_time_tolerance: 
    secs: 0
    nsecs:         0
---
header: 
  seq: 3
  stamp: 
    secs: 1500500184
    nsecs: 468143939
  frame_id: ''
goal_id: 
  stamp: 
    secs: 1500500184
    nsecs: 468120098
  id: /ur_grasping_demo-3-1500500184.468
goal: 
  trajectory: 
    header: 
      seq: 0
      stamp: 
        secs: 0
        nsecs:         0
      frame_id: ''
    joint_names: ['shoulder_pan_joint', 'shoulder_lift_joint', 'elbow_joint', 'wrist_1_joint', 'wrist_2_joint', 'wrist_3_joint']
    points: 
      - 
        positions: [-2.169504467641012, -2.850334946309225, 0.38400888442993164, 0.28067803382873535, -1.1634658018695276, -0.4667428175555628]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        effort: []
        time_from_start: 
          secs: 0
          nsecs:         0
      - 
        positions: [-0.9782418337147725, -1.0965029242347777, 0.8344008878537476, -0.5568656149926419, -1.1294506905802546, -2.7511421082250793]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        effort: []
        time_from_start: 
          secs: 4
          nsecs:         0
  path_tolerance: []
  goal_tolerance: []
  goal_time_tolerance: 
    secs: 0
    nsecs:         0
---
header: 
  seq: 4
  stamp: 
    secs: 1500500222
    nsecs: 231535911
  frame_id: ''
goal_id: 
  stamp: 
    secs: 1500500222
    nsecs: 231486082
  id: /ur_grasping_demo-4-1500500222.231
goal: 
  trajectory: 
    header: 
      seq: 0
      stamp: 
        secs: 0
        nsecs:         0
      frame_id: ''
    joint_names: ['shoulder_pan_joint', 'shoulder_lift_joint', 'elbow_joint', 'wrist_1_joint', 'wrist_2_joint', 'wrist_3_joint']
    points: 
      - 
        positions: [-1.8268087545977991, -1.4274371306048792, 1.6325640678405762, -1.8074730078326624, -1.5595486799823206, 0.056123998016119]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        effort: []
        time_from_start: 
          secs: 0
          nsecs:         0
      - 
        positions: [-0.387, -2.137, 1.432, -0.915, -1.591, 0.071]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        effort: []
        time_from_start: 
          secs: 4
          nsecs:         0
  path_tolerance: []
  goal_tolerance: []
  goal_time_tolerance: 
    secs: 0
    nsecs:         0
```

`follow_joint_trajectory/result` messages:

```yaml
header: 
  seq: 11
  stamp: 
    secs: 1500500149
    nsecs: 693091975
  frame_id: ''
status: 
  goal_id: 
    stamp: 
      secs: 1500500148
      nsecs: 306955099
    id: /ur_grasping_demo-1-1500500148.307
  status: 4
  text: Robot was halted
result: 
  error_code: 0
  error_string: Robot was halted
---
header: 
  seq: 12
  stamp: 
    secs: 1500500178
    nsecs: 853454058
  frame_id: ''
status: 
  goal_id: 
    stamp: 
      secs: 1500500174
      nsecs: 764015913
    id: /ur_grasping_demo-1-1500500174.764
  status: 3
  text: ''
result: 
  error_code: 0
  error_string: Robot was halted
---
header: 
  seq: 13
  stamp: 
    secs: 1500500183
    nsecs:  92835756
  frame_id: ''
status: 
  goal_id: 
    stamp: 
      secs: 1500500179
      nsecs:   4204988
    id: /ur_grasping_demo-2-1500500179.004
  status: 3
  text: ''
result: 
  error_code: 0
  error_string: Robot was halted
---
header: 
  seq: 14
  stamp: 
    secs: 1500500188
    nsecs: 564059925
  frame_id: ''
status: 
  goal_id: 
    stamp: 
      secs: 1500500184
      nsecs: 468120098
    id: /ur_grasping_demo-3-1500500184.468
  status: 3
  text: ''
result: 
  error_code: 0
  error_string: Robot was halted
---
header: 
  seq: 15
  stamp: 
    secs: 1500500226
    nsecs: 346270359
  frame_id: ''
status: 
  goal_id: 
    stamp: 
      secs: 1500500222
      nsecs: 231486082
    id: /ur_grasping_demo-4-1500500222.231
  status: 3
  text: ''
result: 
  error_code: 0
  error_string: Robot was halted
```

The log on the teaching pendant shows (there are no _errors_/_warnings_, just _info_ messages):

```
Program speedj started
Program speedj stopped
```

**Comment by gavanderhoorn** [comment]
@atenpas: I only see msgs on the `result` topic with this:

```yaml
result: 
  error_code: 0
  error_string: Robot was halted
```

That should only be returned in case the driver believes the robot has been emergency or protective stopped:

https://github.com/ThomasTimm/ur_modern_driver/blob/af6edc8a3552c449d27076db1642adf8afa97714/src/ur_ros_wrapper.cpp#L780-L787

I'm assuming that wasn't the case?
