### ISSUE TITLE
Corrupted joint_states are published with ur_sim and real robot (1.8.x).

### ISSUE THREAD

**Issue by jettan** [ThomasTimm/ur_modern_driver#25]
While using the driver to interface with both (but not at the same time) a ur-sim instance (v1.8.14035) and a real controller (CB2, also v1.8.14035), we sometimes observe `JointState` messages that have some really strange values in some of the `position` and `velocity` arrays. An example is pasted below:
```yaml
header: 
  seq: 17396
  stamp: 
    secs: 1448973318
    nsecs: 95394434
  frame_id: ''
name: ['shoulder_pan_joint', 'shoulder_lift_joint', 'elbow_joint', 'wrist_1_joint', 'wrist_2_joint', 'wrist_3_joint']
position: [0.0008817444019501054, 0.0, 0.0, 0.0, -4.737910152973887e+226, 3.4403246606906987e-246]
velocity: [5.356556342585614e-69, -4.555528633092074e-39, -3.501131509392264e-164, -4.0975983370358134e-95, 2.139376420684511e+253, 1.1701194070372343e-307]
effort: [0.0, 0.0, 0.0, 0.0, 0.0, 8.0963e-320]
```
Notice the `-4.737910152973887e+226` and `3.4403246606906987e-246` in the `position` array.

Could this be an off-by-one error in the de-serialisation routines?
